WIP: If no geofence is found map then use default value
adriankumpf/teslamate pull request #2564
Opened 2022-03-30 00:49 UTC by brianmay

This is required because the default value is "" which tells the mqtt
server to delete the retained value.

This in turn means that applications that care about when the car is in
a unknown location will not get the retained value.

This is a bit different from all of the other values in
`@always_published`. For them "" is only published if the value is
unknown or an error occurred. So it makes sense to delete the retained
value.

In this case however, a value of "" generally means "the car is outside
any known geofence" which is a valid condition it itself, and it should
be retained.

There was speculation this might affect the shift_state, but
unfortunately this was not followed up with any evidence or details.

There are any number of solutions that could be deployed here. The
advantage of this solution however is it is not going to break anything
unless you specifically define the TESLAMATE_DEFAULT_GEOFENCE variable.

Fixes: #1336

2022-03-30 00:51 UTC, brianmay commented
Still in the process of testing this to make sure it works. I think I just noticed a problem already, will fix.

This perhaps isn't the perfect solution. But this solution unlike others I can think of avoids breaking the existing API.

2022-03-30 01:47 UTC, brianmay commented
As far as I can tell that test failure is unrelated to anything I did...

2022-03-30 02:22 UTC, brianmay commented
Tests have been successful so far. Set `TESLAMATE_DEFAULT_GEOFENCE` to "nowhere" and Tesla reported it was "nowhere" instead of "".

2022-06-24 12:31 UTC, adriankumpf requested changes
That's pragmatic solution to this long-standing issue 👍

Could you add a brief description of that env variable to `website/docs/configuration/environment_variables.md`?

2022-06-24 12:31 UTC, adriankumpf commented on config/runtime.exs
> +  default_geofence: System.get_env("TESLAMATE_DEFAULT_GEOFENCE")
Let's drop the `TESLAMATE_` prefix for the sake of consistency.

2022-06-24 12:49 UTC, adriankumpf commented
> As far as I can tell that test failure is unrelated to anything I did.
> 
> LATER: I notice other PRs are failing on the same test. So probably a flaky test I think.

Yup, there are a bunch of flaky tests that really need to be fixed

2022-06-25 23:19 UTC, brianmay commented
> Could you add a brief description of that env variable to `website/docs/configuration/environment_variables.md`?

Done.

2022-07-15 08:59 UTC, merged