Add cost per KWh to charges dashboard.
adriankumpf/teslamate pull request #2644
Opened 2022-05-08 19:31 UTC by jyothri

Added a new column to show how economic the charges at the location has been. 
Not all sessions are equal i.e some charge by KWh, some by time. Additionally there could be a flat session charge.

2022-05-31 02:04 UTC, jyothri commented
Hi @adriankumpf 
Wanted to check if I can get an estimate of when this could be addressed?

Thanks,
Jyothrilinga.

2022-06-24 11:29 UTC, adriankumpf requested changes

2022-06-24 11:29 UTC, adriankumpf commented on grafana/dashboards/charges.json
> +          "rawSql": "WITH data AS (\n    SELECT\n        (round(extract(epoch FROM start_date) - 10) * 1000) AS start_date_ts,\n        (round(extract(epoch FROM end_date) + 10) * 1000) AS end_date_t
TeslaMate calculates the total cost using `charge_energy_added` or `charge_energy_used`, whichever is higher.  This should be reflected here too:

```sql    
cost/NULLIF(greatest(charge_energy_added, charge_energy_used), 0)  as cost_per_kwh
```

2022-06-24 11:29 UTC, adriankumpf commented on grafana/dashboards/charges.json
> +            "properties": [
A fixed column width would be neat. 130 should be enough.

2022-06-24 13:17 UTC, adriankumpf commented
Superseded by #2693. Thank you anyway!

2022-06-24 13:17 UTC, closed without merging